const GET_POST_LIST = "GET_POST_LIST"
const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS"
const GET_MORE_POST_LIST = "GET_MORE_POST_LIST"
const GET_MORE_POST_LIST_SUCCESS = "GET_MORE_POST_LIST_SUCCESS"
const STORE_TITLE_FOR_REGISTER = "STORE_TITLE_FOR_REGISTER"
const POST_REGISTER = "POST_REGISTER"
const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS"

export const ActionTypes = {
  GET_POST_LIST,
  GET_POST_LIST_SUCCESS,
  GET_MORE_POST_LIST,
  GET_MORE_POST_LIST_SUCCESS,
  STORE_TITLE_FOR_REGISTER,
  POST_REGISTER,
  POST_REGISTER_SUCCESS,
}
