const GET_POST_LIST = "GET_POST_LIST"
const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS"
const GET_MORE_POST_LIST = "GET_MORE_POST_LIST"
const GET_MORE_POST_LIST_SUCCESS = "GET_MORE_POST_LIST_SUCCESS"

export const ActionTypes = {
  GET_POST_LIST,
  GET_POST_LIST_SUCCESS,
  GET_MORE_POST_LIST,
  GET_MORE_POST_LIST_SUCCESS,
}
