const LOGIN_USER = "LOGIN_USER"
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
const LOGOUT_USER = "LOGOUT_USER"
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
const CLEAR_TOKEN = "CLEAR_TOKEN"

export const ActionTypes = {
  LOGIN_USER,
  LOGIN_USER_SUCCESS,
  LOGOUT_USER,
  LOGOUT_USER_SUCCESS,
  CLEAR_TOKEN,
}
